### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by RoyJing** [dnsjava/dnsjava#128]
After our app was released, we had a lot of crashes like this. The SDK version is 3.0.2, this detailed stack information

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
       at org.xbill.DNS.Client.processReadyKeys(Client.java:76)
       at org.xbill.DNS.Client.runSelector(Client.java:62)
       at org.xbill.DNS.Client.lambda$0sA5rH6uGccjnOr0bSKw-Jywrsk(Client.java)
       at o.-$$Lambda$fli$0sA5rH6uGccjnOr0bSKw-Jywrsk.run(-.java)
       at java.lang.Thread.run(Thread.java:764)

**Comment by ibauersachs** [comment]
The current version is 3.2.2. I cannot support older versions and the particular issue IMO fixed in 3.0.3.

**Comment by RoyJing** [comment]
> I cannot support older versions and the particular issue was AFAIK fixed in 3.1.0.

Great, I'll upgrade to the latest version.
