### ISSUE TITLE
 java.util.NoSuchElementException

### ISSUE THREAD

**Issue by RoyJing** [dnsjava/dnsjava#130]
After our app was released, we had a lot of crashes like this. The SDK version is 3.0.2, this detailed stack information

Fatal Exception: java.util.NoSuchElementException
       at java.util.AbstractQueue.remove(AbstractQueue.java:117)
       at org.xbill.DNS.NioUdpClient.processPendingRegistrations(NioUdpClient.java:70)
       at org.xbill.DNS.NioUdpClient.lambda$ypDlJYLM0ydV48iXzGn6PKZID5U(NioUdpClient.java)
       at o.-$$Lambda$fpt$ypDlJYLM0ydV48iXzGn6PKZID5U.run(-.java)
       at o.-$$Lambda$-5sWpTl5VilOfRvO5qFX7QZvSfI.accept(-.java:2)
       at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:837)
       at org.xbill.DNS.Client.runSelector(Client.java:59)
       at org.xbill.DNS.Client.lambda$jAWiqsJXxSKrE-3ZAhrF3bfbwqQ(Client.java)
       at o.-$$Lambda$fnu$jAWiqsJXxSKrE-3ZAhrF3bfbwqQ.run(-.java)
       at java.lang.Thread.run(Thread.java:764)

**Comment by ibauersachs** [comment]
The current version is 3.2.2. I cannot support older versions and the particular issue was AFAIK fixed in 3.1.0.

**Comment by RoyJing** [comment]
> The current version is 3.2.2. I cannot support older versions and the particular issue was AFAIK fixed in 3.1.0.

Great, I'll upgrade to the latest version
