### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths; When running on Android 7.0.0

### ISSUE THREAD

**Issue by i-m-aman** [dnsjava/dnsjava#232]
I am getting this error when trying to run it on Android Nougat(API 24).

```
compileSdkVersion 30
    buildToolsVersion '28.0.3'
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        multiDexEnabled true
    }
```

I am trying to update the library but Paths is introduced in API 26+ I think.

Before this error, I was getting 

`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;`

this error which I resolved using desugaring API provided by Android

Now, I am getting this.

I cannot update the minSDKversion to 26 now so should I be using the older version of this API?

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at org.xbill.DNS.hosts.HostsFileParser.<init>(HostsFileParser.java:50)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at org.xbill.DNS.Lookup.refreshDefault(Lookup.java:107)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at org.xbill.DNS.Lookup.<clinit>(Lookup.java:111)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at org.xbill.DNS.Lookup.getDefaultResolver(Lookup.java)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at com.khaalijeb.inkdrops.Networking.NetworkingUtils.EasyDns.init(EasyDns.java:60)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at com.khaalijeb.inkdrops.Networking.NetworkingUtils.EasyDns.lookup(EasyDns.java:32)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at com.khaalijeb.inkdrops.SSLClass$1.intercept(SSLClass.java:338)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at java.lang.Thread.run(Thread.java:760)
11-08 23:39:37.682 E/AndroidRuntime( 9298): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/data/app/com.khaalijeb.inkdrops.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.khaalijeb.inkdrops.debug-1/lib/arm64, /data/app/com.khaalijeb.inkdrops.debug-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-08 23:39:37.682 E/AndroidRuntime( 9298): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)**
```

Please suggest me a way to update the library and work it on the device below API 26.

Thanks for your time.

**Comment by ibauersachs** [comment]
You might be able to use `LookupSession` to avoid instantiating the `HostsFileParser`. There are other APIs from Java 8 used, notably from `java.time` that are not natively available prior to API level 26.

> Please suggest me a way to update the library and work it on the device below API 26.

Have you tried Android's _desugaring_? If the above suggestion and desugaring doesn't work, there's no workaround.

**Comment by i-m-aman** [comment]
Hey Sorry to reply so late on this. Can you please describe how to use LookupSession?

Currently, I am using like this - 

```
try {
            // configure the resolvers, starting with the default ones (based on the current network connection)
            Resolver defaultResolver = Lookup.getDefaultResolver();
            // use Google's public DNS services
            Resolver googleFirstResolver = new SimpleResolver("8.8.8.8");
            Resolver googleSecondResolver = new SimpleResolver("8.8.4.4");
            // also try using Amazon
            //Resolver amazonResolver = new SimpleResolver("205.251.198.30");
            Log.d("upisdk", "defaultResolver: " + defaultResolver);
            Lookup.setDefaultResolver(new ExtendedResolver(new Resolver[]{
                    defaultResolver, googleFirstResolver, googleSecondResolver/*amazonResolver*/}));
        } catch (UnknownHostException e) {
            //Log.w("DNS", "Couldn't initialize custom resolvers");
        } catch (ExceptionInInitializerError e) {
            //Log.w("DNS", "ExceptionInInitializerError");
        } catch (NoClassDefFoundError e) {
            Log.d("DNS", "NoClassDefFoundError");
        } catch (Exception e) {

        }
```

On Devices running Android 7.0.0 or other below API 26, I am getting the error. Also, I am unable to catch the error like `NoClassDefFoundError` which leads to crashes.

**Comment by ibauersachs** [comment]
The [examples](https://github.com/dnsjava/dnsjava/blob/master/EXAMPLES.md#get-the-mx-target-and-preference-of-a-name-modern) contain a demo using the LookupSession.

`NoClassDefFoundError`s are thrown when the class is first loaded, which depending on the classloader in use is as early as the `import` statement. See https://github.com/dnsjava/dnsjava/issues/112#issuecomment-640046219 for a detailed explanation. That issue also has links to commits that work around the problem.
