### ISSUE TITLE
bad compression exception

### ISSUE THREAD

**Issue by soufianbenafia** [dnsjava/dnsjava#238]
Following exception occured while my dns server was receiving queries:

```
Exception in thread "main" org.xbill.DNS.WireParseException: bad compression
        at org.xbill.DNS.Name.<init>(Name.java:376)
        at org.xbill.DNS.Record.fromWire(Record.java:178)
        at org.xbill.DNS.Message.<init>(Message.java:111)
        at org.xbill.DNS.Message.<init>(Message.java:143)
        at DNS_Server.main(DNS_Server.java:112)

```

**Comment by nresare** [comment]
Interesting. This might be because of a bug in dnsjava or it might be because of a malformed message being sent to the server. Are you able to narrow down what message that caused this, ideally into a self contained test case?

**Comment by soufianbenafia** [comment]
I just checked the network traffic in Wireshark that passed today while the DNS server was running and I found several malformed packets being sent today.
