### ISSUE TITLE
Message class cannot handle truncated record

### ISSUE THREAD

**Issue by soufianbenafia** [dnsjava/dnsjava#240]
My DNS Server broke down while it was running due an exception that occured while it was trying to parse a truncated record in the message class:

```
Exception in thread "main" org.xbill.DNS.WireParseException: truncated record
        at org.xbill.DNS.Record.newRecord(Record.java:78)
        at org.xbill.DNS.Record.fromWire(Record.java:191)
        at org.xbill.DNS.Message.<init>(Message.java:111)
        at org.xbill.DNS.Message.<init>(Message.java:143)
        at DNS_Server.main(DNS_Server.java:61)
```

**Comment by ibauersachs** [comment]
dnsjava is telling you that it can't decode the message because it's incomplete - it's up to you what to do about that.
