### ISSUE TITLE
Support native image

### ISSUE THREAD

**Issue by MaysonD** [dnsjava/dnsjava#274]
Would be nice to use this great library in Java native image

**Comment by ibauersachs** [comment]
See #182

**Comment by MaysonD** [comment]
Thanks, but mostly problem in that: Error encountered while parsing org.xbill.DNS.ResolverConfig.<init>() 

Full stacktrace

`Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.xbill.DNS.ResolverConfig.<init>() 
Parsing context:
   at org.xbill.DNS.ResolverConfig.<init>(ResolverConfig.java:92)
   at org.xbill.DNS.ResolverConfig.refresh(ResolverConfig.java:86)
   at org.xbill.DNS.ResolverConfig.checkInitialized(ResolverConfig.java:59)
   at org.xbill.DNS.ResolverConfig.getCurrentConfig(ResolverConfig.java:65)
   at org.xbill.DNS.lookup.LookupSession.defaultBuilder(LookupSession.java:354)
   at com.lejme.guestposter.verification.service.DnsService.getDomainDNSTxtRecords(DnsService.java:32)
   at com.lejme.guestposter.verification.service.DnsService_ClientProxy.getDomainDNSTxtRecords(Unknown Source)
   at com.lejme.guestposter.verification.service.DomainOwnerVerificationService.verifyByDnsTxt(DomainOwnerVerificationService.java:93)
   at com.lejme.guestposter.verification.service.DomainOwnerVerificationService$$Lambda$1145/0x0000000302f3e118.apply(Unknown Source)
   at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
   at com.oracle.svm.core.jdk.Target_java_lang_StackWalker$AbstractStackFrameSpliterator.tryAdvance(Target_java_lang_StackWalker.java:216)
   at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
   at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
   at java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
   at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
   at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
   at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
   at java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
   at java.util.stream.IntPipeline.findFirst(IntPipeline.java:552)
   at java.text.DecimalFormatSymbols.findNonFormatChar(DecimalFormatSymbols.java:844)
   at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:823)
   at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:115)
   at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
   at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:182)
   at java.util.Formatter.zero(Formatter.java:2450)
   at java.util.Formatter$FormatSpecifier.getZero(Formatter.java:4450)
   at java.util.Formatter$FormatSpecifier.localizedMagnitude(Formatter.java:4466)
   at java.util.Formatter$FormatSpecifier.print(Formatter.java:3530)
   at java.util.Formatter$FormatSpecifier.print(Formatter.java:3412)
   at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2972)
   at java.util.Formatter$FormatSpecifier.print(Formatter.java:2924)
   at java.util.Formatter.format(Formatter.java:2678)
   at java.util.Formatter.format(Formatter.java:2625)
   at java.lang.String.format(String.java:4143)
   at jdk.internal.util.Preconditions.outOfBoundsMessage(Preconditions.java:206)
   at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
   at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
   at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
   at java.util.Objects.checkIndex(Objects.java:359)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:61)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.xbill.DNS.config.WindowsResolverConfigProvider$InnerWindowsResolverConfigProvider.<init>(org.xbill.DNS.config.WindowsResolverConfigProvider$1). This error is reported at image build time because class org.xbill.DNS.config.WindowsResolverConfigProvider is registered for linking at image build time by command line
        at parsing org.xbill.DNS.config.WindowsResolverConfigProvider.<init>(WindowsResolverConfigProvider.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:180)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1162)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1145)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1003)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:179)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
        ... 13 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.xbill.DNS.config.WindowsResolverConfigProvider$InnerWindowsResolverConfigProvider.<init>(org.xbill.DNS.config.WindowsResolverConfigProvider$1). This error is reported at image build time because class org.xbill.DNS.config.WindowsResolverConfigProvider is registered for linking at image build time by command line
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:333)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:323)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:279)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1778)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1768)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5287)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
        ... 38 more
`

**Comment by ibauersachs** [comment]
I already mentioned in #182 that I expect a lot more stuff not working with AOT compilation and provided a possible workaround. Neither the author in #182 nor you said if this works. I'm going to close this as at this time it's too much work to make everything in dnsjava AOT ready.
