### ISSUE TITLE
Compilation failure because junit couldn't load class DNSInputTest

### ISSUE THREAD

**Issue by benrkia** [dnsjava/dnsjava#283]
Because of some custom changes I am trying to build the project but I have this issue

```
[jacoco:instrument] Instrumented 287 classes to /home/build/private/coverage/classes
     [echo] Running coverage tests
     [java]
     [java] Thanks for using JUnit! Support its development at https://junit.org/sponsoring
     [java]
     [java] Usage: ConsoleLauncher [-h] [--disable-ansi-colors] [--disable-banner]
     [java]                        [--fail-if-no-tests] [--scan-modules] [--scan-classpath[=PATH[;|:
     [java]                        PATH...]]]... [--details=MODE] [--details-theme=THEME]
     [java]                        [--reports-dir=DIR] [-c=CLASS]... [--config=KEY=VALUE]... [-cp=PATH
     [java]                        [;|:PATH...]]... [-d=DIR]... [-e=ID]... [-E=ID]...
     [java]                        [--exclude-package=PKG]... [-f=FILE]... [--include-package=PKG]...
     [java]                        [-m=NAME]... [-n=PATTERN]... [-N=PATTERN]... [-o=NAME]...
     [java]                        [-p=PKG]... [-r=RESOURCE]... [-t=TAG]... [-T=TAG]... [-u=URI]...
     [java] Launches the JUnit Platform from the console.
     [java]   -h, --help                 Display help information.
     [java]       --disable-ansi-colors  Disable ANSI colors in output (not supported by all
     [java]                                terminals).
     [java]       --disable-banner       Disable print out of the welcome message.
     [java]       --details=MODE         Select an output details mode for when tests are executed.
     [java]                                Use one of: none, summary, flat, tree, verbose. If 'none'
     [java]                                is selected, then only the summary and test failures are
     [java]                                shown. Default: tree.
     [java]       --details-theme=THEME  Select an output details tree theme for when tests are
     [java]                                executed. Use one of: ascii, unicode. Default: unicode.
     [java]       -cp, --classpath, --class-path=PATH[;|:PATH...]
     [java]                              Provide additional classpath entries -- for example, for
     [java]                                adding engines and their dependencies. This option can be
     [java]                                repeated.
     [java]       --fail-if-no-tests     Fail and return exit status code 2 if no tests are found.
     [java]       --reports-dir=DIR      Enable report output into a specified local directory (will
     [java]                                be created if it does not exist).
     [java]       --scan-modules         EXPERIMENTAL: Scan all resolved modules for test discovery.
     [java]   -o, --select-module=NAME   EXPERIMENTAL: Select single module for test discovery. This
     [java]                                option can be repeated.
     [java]       --scan-classpath, --scan-class-path[=PATH[;|:PATH...]]
     [java]                              Scan all directories on the classpath or explicit classpath
     [java]                                roots. Without arguments, only directories on the system
     [java]                                classpath as well as additional classpath entries supplied
     [java]                                via -cp (directories and JAR files) are scanned. Explicit
     [java]                                classpath roots that are not on the classpath will be
     [java]                                silently ignored. This option can be repeated.
     [java]   -u, --select-uri=URI       Select a URI for test discovery. This option can be repeated.
     [java]   -f, --select-file=FILE     Select a file for test discovery. This option can be
     [java]                                repeated.
     [java]   -d, --select-directory=DIR Select a directory for test discovery. This option can be
     [java]                                repeated.
     [java]   -p, --select-package=PKG   Select a package for test discovery. This option can be
     [java]                                repeated.
     [java]   -c, --select-class=CLASS   Select a class for test discovery. This option can be
     [java]                                repeated.
     [java]   -m, --select-method=NAME   Select a method for test discovery. This option can be
     [java]                                repeated.
     [java]   -r, --select-resource=RESOURCE
     [java]                              Select a classpath resource for test discovery. This option
     [java]                                can be repeated.
     [java]   -n, --include-classname=PATTERN
     [java]                              Provide a regular expression to include only classes whose
     [java]                                fully qualified names match. To avoid loading classes
     [java]                                unnecessarily, the default pattern only includes class
     [java]                                names that begin with "Test" or end with "Test" or
     [java]                                "Tests". When this option is repeated, all patterns will
     [java]                                be combined using OR semantics. Default: [^(Test.*|.+[.$]
     [java]                                Test.*|.*Tests?)$]
     [java]   -N, --exclude-classname=PATTERN
     [java]                              Provide a regular expression to exclude those classes whose
     [java]                                fully qualified names match. When this option is repeated,
     [java]                                all patterns will be combined using OR semantics.
     [java]       --include-package=PKG  Provide a package to be included in the test run. This
     [java]                                option can be repeated.
     [java]       --exclude-package=PKG  Provide a package to be excluded from the test run. This
     [java]                                option can be repeated.
     [java]   -t, --include-tag=TAG      Provide a tag or tag expression to include only tests whose
     [java]                                tags match. When this option is repeated, all patterns
     [java]                                will be combined using OR semantics.
     [java]   -T, --exclude-tag=TAG      Provide a tag or tag expression to exclude those tests whose
     [java]                                tags match. When this option is repeated, all patterns
     [java]                                will be combined using OR semantics.
     [java]   -e, --include-engine=ID    Provide the ID of an engine to be included in the test run.
     [java]                                This option can be repeated.
     [java]   -E, --exclude-engine=ID    Provide the ID of an engine to be excluded from the test
     [java]                                run. This option can be repeated.
     [java]       --config=KEY=VALUE     Set a configuration parameter for test discovery and
     [java]                                execution. This option can be repeated.
     [java] org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
     [java] 	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
     [java] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
     [java] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
     [java] 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
     [java] 	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:66)
     [java] 	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:58)
     [java] 	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
     [java] 	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:58)
     [java] 	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:95)
     [java] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:73)
     [java] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:50)
     [java] 	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:43)
     [java] 	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:37)
     [java] Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'org.xbill.DNS.DNSInputTest'] resolution failed
     [java] 	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
     [java] 	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
     [java] 	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
     [java] 	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
     [java] 	... 16 more
     [java] Caused by: org.junit.platform.commons.PreconditionViolationException: Could not load class with name: org.xbill.DNS.DNSInputTest
     [java] 	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:75)
     [java] 	at org.junit.platform.commons.function.Try$Failure.getOrThrow(Try.java:335)
     [java] 	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:74)
     [java] 	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:66)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
     [java] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
     [java] 	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
     [java] 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
     [java] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
     [java] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
     [java] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
     [java] 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
     [java] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     [java] 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
     [java] 	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
     [java] 	... 21 more
     [java] Caused by: java.lang.ClassNotFoundException: org.xbill.DNS.DNSInputTest
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
     [java] 	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:829)
     [java] 	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
     [java] 	at org.junit.platform.commons.function.Try.of(Try.java:93)
     [java] 	at org.junit.platform.commons.function.Try.call(Try.java:57)
     [java] 	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:792)
     [java] 	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:748)
     [java] 	... 36 more
     [java]
     [java] Java Result: 255
```

I am able to make it pass by renaming the class to DNSInputTest, however i'd love to know how are dealing with it?
Thanks in advance

**Comment by ibauersachs** [comment]
What exactly is your environment? Please include OS, JDK, Maven and all versions thereof.
If you have JDK 8+ and Maven 3.8.1+, the project is usually built by simply executing `mvn package`. Please try that on the master or release/3.5.x branch without your changes.

**Comment by benrkia** [comment]
Hi,
Thank you for your reply. I solved the issue.
I am actually using an internal build system that loads classes based on the file names, so i changed it to use class file names instead.
