### ISSUE TITLE
dnsjava 3.6.0: issue with Java 20: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found

### ISSUE THREAD

**Issue by thomas-corte** [dnsjava/dnsjava#329]
With Java 20, the new version 3.6 seems to create an issue, see stack trace below. It's probably related to the new
"Internet-Address Resolution SPI" support feature. There's no problem with Java 22.

Exception in thread "main" java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1812)
	at java.base/java.net.InetAddress.loadResolver(InetAddress.java:480)
	at java.base/java.net.InetAddress.resolver(InetAddress.java:460)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1681)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1004)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1673)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1415)
	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:229)

**Comment by ibauersachs** [comment]
The classes are intentionally compiled for Java 21 because Java 20 is EOL. That's also why you're not seeing a problem with Java 22.

**Comment by cj-arnas-navasinskas** [comment]
@ibauersachs 
Same issue under java 17, does dnsjava 3.6 support java 17 ?

**Comment by ironmaya** [comment]
I have the same issue using Java 22.

This is the stacktrace:
Exception in thread "main" java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1215)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1224)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1269)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1305)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1387)
        at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1800)
        at java.base/java.net.InetAddress.loadResolver(InetAddress.java:508)
        at java.base/java.net.InetAddress.resolver(InetAddress.java:488)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1814)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1149)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1806)
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1919)
        at org.apache.logging.log4j.core.util.NetUtils.getLocalHostname(NetUtils.java:56)
        at org.apache.logging.log4j.core.LoggerContext.lambda$setConfiguration$0(LoggerContext.java:625)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:625)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:713)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:735)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:260)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:258)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:177)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:58)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:32)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:391)
        at spark.Service.<clinit>(Service.java:58)
        at spark.Spark$SingletonHolder.<clinit>(Spark.java:54)
        at spark.Spark.getInstance(Spark.java:58)
        at spark.Spark.<clinit>(Spark.java:64)

**Comment by thomas-corte** [comment]
I can't confirm the issue with Java 22, just with 20 (which is EOL, you're right).
I didn't change my Java 20 application (other than introducing dnsjava 3.6 via Gradle) to encounter the issue.

Anyhow, I see that META-INF contains:

META-INF/versions
META-INF/versions/11
META-INF/versions/11/module-info.class
META-INF/versions/21
META-INF/versions/21/org
META-INF/versions/21/org/xbill
META-INF/versions/21/org/xbill/DNS
META-INF/versions/21/org/xbill/DNS/spi
META-INF/versions/21/org/xbill/DNS/spi/DnsjavaInetAddressResolverProvider.class
META-INF/versions/21/org/xbill/DNS/spi/DnsjavaInetAddressResolver.class
META-INF/versions/21/module-info.class
META-INF/services
META-INF/services/java.net.spi.InetAddressResolverProvider
META-INF/services/sun.net.spi.nameservice.NameServiceDescriptor

I'm not experienced with the Java 9+ service loader mechanism, but I guess the issue here is that some older versions of Java (Java 20 for sure, but apparently not every version >= 9) do pick up the descriptor in META-INF/services/java.net.spi.InetAddressResolverProvider and try to load the class listed therein, however only Java versions >= 21 will also see the respective class files.

**Comment by ibauersachs** [comment]
Thanks for the clarifications. I'll need to check if I can move the SPI definition also into the versioned subfolder, not just the class files.

I'm not sure if it's still possible to target Java 18, but even if it is, I don't quite see the point (once the SPI issue would be fixed of course).

**Comment by cj-arnas-navasinskas** [comment]
In our case it seems jacoco is not happy:

`*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Process 'Gradle Test Executor 286' finished with non-zero exit value 134
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 286' finished with non-zero exit value 134
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:145)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:42)
	at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:245)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:157)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy109.executionFinished(Unknown Source)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:221)
	at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:355)
	at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:110)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1812)
	at java.base/java.net.InetAddress.loadResolver(InetAddress.java:479)
	at java.base/java.net.InetAddress.resolver(InetAddress.java:459)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1671)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1003)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1663)
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1776)
	at org.jacoco.agent.rt.internal_b6258fc.Agent.createSessionId(Agent.java:180)
	at org.jacoco.agent.rt.internal_b6258fc.Agent.startup(Agent.java:125)
	at org.jacoco.agent.rt.internal_b6258fc.Agent.getInstance(Agent.java:54)
	at org.jacoco.agent.rt.internal_b6258fc.PreMain.premain(PreMain.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 3 more`

**Comment by ibauersachs** [comment]
@cj-arnas-navasinskas You're definitely not running on Java 17, the stacktrace clearly shows that you're on Java 18 or newer. The method `java.net.InetAddress.loadResolver` doesn't exist on Java 17 (see the source here: https://github.com/openjdk/jdk/blob/jdk-17%2B35/src/java.base/share/classes/java/net/InetAddress.java). Based on the line number, my guess is you're on Java 20 (https://github.com/openjdk/jdk/blob/jdk-20%2B36/src/java.base/share/classes/java/net/InetAddress.java#L479).

Java 20 is EOL.

**Comment by cj-arnas-navasinskas** [comment]
@ibauersachs this stack trace might've been with java 19, intellij is stubborn. Anyway it works after fix, thanks !

**Comment by ediweissmann** [comment]
I'm still seeing this issue using dnsjava `3.6.1` under JDK 21.0.3 with the `--enable-preview` java option.

**Comment by ibauersachs** [comment]
@maffe Your usage of the shade plugin breaks things. Mark the jar as Multi-Release and it'll work. See e.g. https://stackoverflow.com/a/54713830
