### ISSUE TITLE
Failed to resolve org.xbill.DNS in DNSJava 3.6.x

### ISSUE THREAD

**Issue by karthickm512** [dnsjava/dnsjava#332]
Hi,

We have been using DNSJava 3.5.2 in our Apache Karaf 4.4.4 and while stepping to 3.6.1 version, we are getting the following exception 

```
filter:="(&(osgi.wiring.package=org.xbill.DNS)(version>=3.6.0)(!(version>=4.0.0)))"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:256)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Note: We are using Java 11

Could anyone throw light on what needs to be done? We hadnt explicitly added the "org.xbill.DNS" artifact earlier (while using 3.5.2) as well now.

**Comment by ibauersachs** [comment]
I don't know Karaf and only worked with Felix directly. Usually the stacktrace was much longer and contained more details about the resolution.

The manifest of dnsjava 3.6.1 still has OSGi metadata, and it also has `Export-Package: org.xbill.DNS;version="3.6.1"`. Can you create an example project that reproduces the problem?

**Comment by ajzach** [comment]
We have a similar problem; in our case, we are using Java 21 and Jooby 1.6.9:

```
Exception in thread "main" java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1812)
	at java.base/java.net.InetAddress.loadResolver(InetAddress.java:508)
	at java.base/java.net.InetAddress.resolver(InetAddress.java:488)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1826)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1931)
	at java.management/sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:144)
	at java.management/sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
	at org.jooby.internal.JvmInfo.pid(JvmInfo.java:215)
	at org.jooby.Jooby.<clinit>(Jooby.java:813)
```

**Comment by ibauersachs** [comment]
Same question: please provide an example reproducer project.

**Comment by ajzach** [comment]
App.java

```java
package org.example;

import org.jooby.Jooby;

public class App extends Jooby {

  {
    get("/", () -> "Hello World!");
  }

  public static void main(final String[] args) {
    run(App::new, args);
  }
}
```

pom.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>test-jooby</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>test-jooby</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <finalName>test</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>org.example.App</mainClass>
                        </manifest>
                    </archive>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jooby</groupId>
            <artifactId>jooby</artifactId>
            <version>1.6.9</version>
        </dependency>
        <dependency>
            <groupId>dnsjava</groupId>
            <artifactId>dnsjava</artifactId>
            <version>3.6.0</version>
        </dependency>
    </dependencies>
</project>
```

Running mvn -Dmaven.test.skip=true clean compile package; java -jar target/test.jar results in the error.

**Comment by ibauersachs** [comment]
Your problem is the maven-assembly-plugin. You're creating a new jar, but don't respect the existing manifest. Dnsjava is a multi-release jar, so you need to reflect that in your wrapping.

**Comment by ajzach** [comment]
With version 3.5.3, I'm not having this problem.

**Comment by ajzach** [comment]
By adding the following configuration, I was able to get it to work:

```xml
                    <manifestEntries>
                        <Multi-Release>true</Multi-Release>
                    </manifestEntries>
```

Thank you
