### ISSUE TITLE
 Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration

### ISSUE THREAD

**Issue by Krishnasony** [dnsjava/dnsjava#352]
I'm started getting crash while using dns java library for custom DNS. 
It is coming on Android 7 only
```
          Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
       at org.xbill.DNS.SimpleResolver.<init>(SimpleResolver.java:47)
       at in.porter.customerapp.shared.network.dns.CustomDns.lookup(CustomDns.kt:21)
       at in.porter.customerapp.shared.network.dns.SequentialDns.lookup(SequentialDns.kt:20)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:28)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by Krishnasony** [comment]
Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.theporter.android.customerapp-2/base.apk", zip file "/data/app/com.theporter.android.customerapp-2/split_config.armeabi_v7a.apk", zip file "/data/app/com.theporter.android.customerapp-2/split_config.en.apk", zip file "/data/app/com.theporter.android.customerapp-2/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.theporter.android.customerapp-2/lib/arm, /data/app/com.theporter.android.customerapp-2/base.apk!/lib/armeabi-v7a, /data/app/com.theporter.android.customerapp-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.theporter.android.customerapp-2/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.theporter.android.customerapp-2/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at org.xbill.DNS.SimpleResolver.<init>(SimpleResolver.java:47)
       at in.porter.customerapp.shared.network.dns.CustomDns.lookup(CustomDns.kt:21)
       at in.porter.customerapp.shared.network.dns.SequentialDns.lookup(SequentialDns.kt:20)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:28)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by Krishnasony** [comment]
> ```
>       Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
>    at org.xbill.DNS.SimpleResolver.<init>(SimpleResolver.java:47)
>    at in.porter.customerapp.shared.network.dns.CustomDns.lookup(CustomDns.kt:21)
>    at in.porter.customerapp.shared.network.dns.SequentialDns.lookup(SequentialDns.kt:20)
>    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
>    at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
>    at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
>    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
>    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
>    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
>    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
>    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
>    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
>    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
>    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
>    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>    at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:28)
>    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
>    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
>    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>    at java.lang.Thread.run(Thread.java:761)
> ```

**Comment by ibauersachs** [comment]
Google for "Android" and "java.time.Duration".

**Comment by Krishnasony** [comment]
> Google for "Android" and "java.time.Duration".

Does dnsjava library not support API levels below 26?
