### ISSUE TITLE
DnsjavaInetAddressResolverProvider not found

### ISSUE THREAD

**Issue by ljy1058318852** [dnsjava/dnsjava#363]
【ERROR】：
```
java.util.ServiceConfigurationError: java.net.spi.InetAddressResolverProvider: Provider org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
```
【Env】：
```
<manifestEntries>
    <Multi-Release>true</Multi-Release> 
</manifestEntries>

<dependency>
    <groupId>dnsjava</groupId>
    <artifactId>dnsjava</artifactId>
    <version>3.6.2</version>
</dependency>
        
java21 windows
```

【my pom.xml】：
```……
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.12.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Multi-Release>true</Multi-Release> 
                                    </manifestEntries>
                                    <mainClass>com.potato.potatotool.ToStart</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <jlinkImageName>PotatoTool</jlinkImageName>
                    <launcher>launcher</launcher>
                    <mainClass>com.potato.potatotool/com.potato.potatotool.ToStart</mainClass>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <attach>true</attach>
                    <attachArtifactClassifier>jdk11+</attachArtifactClassifier>
                    <libs>
                        <lib>${java.home}/jmods/</lib>
                    </libs>
                    <obfuscate>true</obfuscate>
                    <injar>${project.build.finalName}.jar</injar>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                    <proguardInclude>${project.basedir}/proguard.conf</proguardInclude>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <configuration>
                            <tasks>
                                <mkdir dir="${project.basedir}/outJar"/>
                                <copy file="${project.build.directory}/${project.build.finalName}-jdk11+.jar"
                                      tofile="${project.basedir}/outJar/${project.build.finalName}-jdk11+.jar"
                                      force="true" />
                            </tasks>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
```

**Comment by ibauersachs** [comment]
Find out why `DnsjavaInetAddressResolverProvider` is not part of the jar(s) you produce. Start with a clean Maven build that doesn't do any shading/obfuscation/classifier fiddling.

In any case, this is an issue with your build setup, not with dnsjava.

**Comment by aghasemi** [comment]
Hi. I have the same problem, and it happens with versions 3.6.0 and above only: Downgrading to 3.5.3 always solves the issue. Any idea what could have changed? If it helps, the stack trace shows the issue originates from Google OAuth library.

**Comment by phax** [comment]
Might there be an issue due to the Java version used? Because DNSJava uses the multiversion JAR file layout (can't recall the exact term), the actual Java version used makes a difference - so try with Java 17 and Java 21 and see if it makes a difference
