### ISSUE TITLE
Custom Java 8 DNS SPI is causing deadlock

### ISSUE THREAD

**Issue by AnveshMora** [dnsjava/dnsjava#69]
Hi Team,

I've been observing deadlock on dnsjava: 2.1.8 in our production. Any help will be more appreciated.

And I saw same bug raised in https://sourceforge.net/p/dnsjava/bugs/43/, before migrating to github. I couldn't figure out if issue was fixed or any traces of action their and in git hub.

Below is the thread dump:

```
"Attach Listener" #32 daemon prio=9 os_prio=0 tid=0x00007f317c001000 nid=0x8aa7 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"class org.xbill.DNS.SimpleResolver: 89.239.209.18.in-addr.arpa." #31 daemon prio=5 os_prio=0 tid=0x00007f312403d000 nid=0x1daa waiting for monitor entry [0x00007f31cd4ad000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.security.Permissions.implies(Permissions.java:178)
        - waiting to lock <**0x00000000c03cb4c8**> (a java.security.Permissions)
        at sun.security.provider.PolicyFile.implies(PolicyFile.java:1083)
        at java.security.ProtectionDomain.implies(ProtectionDomain.java:279)
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:450)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:689)
        - locked <0x00000000f85d3058> (a java.lang.Object)
        - locked <0x00000000f85d3048> (a java.lang.Object)
        - locked <0x00000000f85d3038> (a java.lang.Object)
        at sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91)
        at org.xbill.DNS.UDPClient.bind_random(UDPClient.java:75)
        at org.xbill.DNS.UDPClient.bind(UDPClient.java:90)
        at org.xbill.DNS.UDPClient.sendrecv(UDPClient.java:149)
        at org.xbill.DNS.SimpleResolver.send(SimpleResolver.java:257)
        at org.xbill.DNS.ResolveThread.run(ResolveThread.java:37)

   Locked ownable synchronizers:
        - None

"class org.xbill.DNS.SimpleResolver: 89.239.209.18.in-addr.arpa." #30 daemon prio=5 os_prio=0 tid=0x00007f312400e800 nid=0x1da9 waiting for monitor entry [0x00007f31cf22c000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.security.Permissions.implies(Permissions.java:178)
        - waiting to lock <0x00000000c03cb4c8> (a java.security.Permissions)
        at sun.security.provider.PolicyFile.implies(PolicyFile.java:1083)
        at java.security.ProtectionDomain.implies(ProtectionDomain.java:279)
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:450)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkListen(SecurityManager.java:1131)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:689)
        - locked <**0x00000000f84f88b0**> (a java.lang.Object)
        - locked <**0x00000000f84f88a0**> (a java.lang.Object)
        - locked <**0x00000000f84f8890**> (a java.lang.Object)
        at sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91)
        at org.xbill.DNS.UDPClient.bind_random(UDPClient.java:75)
        at org.xbill.DNS.UDPClient.bind(UDPClient.java:90)
        at org.xbill.DNS.UDPClient.sendrecv(UDPClient.java:149)
        at org.xbill.DNS.SimpleResolver.send(SimpleResolver.java:257)
        at org.xbill.DNS.ResolveThread.run(ResolveThread.java:37)

   Locked ownable synchronizers:
        - None

"1-EP" #23 prio=5 os_prio=0 tid=0x00007f3204708000 nid=0x795 in Object.wait() [0x00007f31d54eb000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000f78cdb78> (a org.xbill.DNS.ExtendedResolver$Resolution)
        at java.lang.Object.wait(Object.java:502)
        at org.xbill.DNS.ExtendedResolver$Resolution.start(ExtendedResolver.java:111)
        - locked <0x00000000f78cdb78> (a org.xbill.DNS.ExtendedResolver$Resolution)
        at org.xbill.DNS.ExtendedResolver.send(ExtendedResolver.java:358)
        at org.xbill.DNS.Lookup.lookup(Lookup.java:477)
        at org.xbill.DNS.Lookup.resolve(Lookup.java:529)
        at org.xbill.DNS.Lookup.run(Lookup.java:541)
        at DNS.spi.MCD.getHostByAddr(MCD.java:149)
        at DNS.spi.MCD.invoke(MCD.java:82)
        at com.sun.proxy.$Proxy0.getHostByAddr(Unknown Source)
        at java.net.InetAddress.getHostFromNameService(InetAddress.java:618)
        at java.net.InetAddress.getHostName(InetAddress.java:560)
        at java.net.SocketPermission.getCanonName(SocketPermission.java:666)
        at java.net.SocketPermission.impliesIgnoreMask(SocketPermission.java:968)
        at java.net.SocketPermissionCollection.implies(SocketPermission.java:1402)
        - locked <0x00000000c03cb858> (a java.net.SocketPermissionCollection)
        at java.security.Permissions.implies(Permissions.java:182)
        - locked <0x00000000c03cb4c8> (a java.security.Permissions)
```

Regards,
Anvesh Mora

**Comment by ibauersachs** [comment]
This most likely isn't a deadlock in dnsjava but rather between your custom SPI (`net.secureworks.sherlock.modularcollector.DNS.spi.ModularCollectorDomainNameService`) and Java. It's probably because the affected code runs with a SecurityManager (the SecurityManager tries to check if the scripted code is allowed to contact the DNS servers, and dnsjava waits for this permission from the SecurityManager).

This chicken-egg problem is one of the reasons the SPI has been removed from Java 9+, see [JDK-8134577](https://bugs.openjdk.java.net/browse/JDK-8134577). You might be lucky by doing something like in jitsi/dnsjava@691238172a678de64ad411b3c5d678bbf2c2ca0e, but you'd better look for an alternative (i.e. non-SPI) solution.

**Comment by AnveshMora** [comment]
We did give SocketPermission for a range of ports in policy file. is this something different from what you are suggesting?

**Comment by ibauersachs** [comment]
The _validation_ of the SocketPermission by the SecurityManager is causing the deadlock. At the very least you need to avoid name resolution by the SecurityManager, i.e. prevent it from calling `getHostName`. If you currently allow something like

    permission java.net.SocketPermission "google-public-dns-a.google.com:53", "connect, accept"

try using an IP address:

    permission java.net.SocketPermission "8.8.8.8:53", "connect, accept"

**Comment by AnveshMora** [comment]
@ibauersachs , We have configured like this :

permission java.net.SocketPermission "*:53", "connect, accept"

**Comment by AnveshMora** [comment]
@ibauersachs and one more thing I'm concerned is, in below lines in Resolution the process is indefinitely looped waiting for response from resolution handlers and this happens after handling exception. 

https://github.com/dnsjava/dnsjava/blob/e0fe7fbd2378b55d9248da87e4b04d69e1968dda/src/main/java/org/xbill/DNS/ExtendedResolver.java#L103-L115

This is kind of raising suspicion of why we have to this and is this the culprit because it's already holding couple of locks and waiting for other lock to acquisition.

Correct me if I'm wrong.

**Comment by ibauersachs** [comment]
There is a bug, yes, but it's only not properly handling the InterruptedException. I'll fix this in an upcoming version.
But, as I said: this is NOT your deadlock! The deadlock is on object 0x00000000c03cb4c8, which an instance of `java.security.Permissions`. Please re-read my first comment and the Javadoc of `java.net.SocketPermission.getCanonName`.

**Comment by AnveshMora** [comment]
Okay sure @ibauersachs , I'll go through that and i need couple of clarifications from and after that I should be good to go . So I need clarification on below things :

1. permission java.net.SocketPermission "*:53", "connect, resolve"  , we have this line in our policy file. Is this not right? supposed to not cause the issue? and 
2. How would I let SecurityManager know that my custom SPI is trying to contact the DNS servers and it should allow it.

**Comment by ibauersachs** [comment]
You can't. It's not an issue of the SecurityManager. You're running into the issue why the SPI was removed from Java 9+. The only way to workaround that is to somehow prevent your custom SPI to perform an actual reverse lookup for the DNS server's addresses and ignore the SecurityManager's request. How you do that and how it affects the rest of your application/framework is up to you.
