### ISSUE TITLE
persistence across sessions 

### ISSUE THREAD

**Issue by vikasrathore** [dnsjava/dnsjava#73]
Does this code write Records in some kind for persistence storage(file, database etc). so that it can be reused across sessions.

**Comment by vikasrathore** [comment]
If i am use this 

Lookup.setDefaultCache(getCache(Environment.getExternalStorageDirectory()+ "/dnscache.txt"), DClass.IN);

i get this error 

2019-08-06 14:03:52.380 4587-4620/network.paytm.com.networkmoduleapp W/System.err: java.io.FileNotFoundException: /storage/emulated/0/dnscache.txt (No such file or directory)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at java.io.FileInputStream.open0(Native Method)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at org.xbill.DNS.Tokenizer.<init>(Tokenizer.java:160)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at org.xbill.DNS.Master.<init>(Master.java:39)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at org.xbill.DNS.Master.<init>(Master.java:74)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at org.xbill.DNS.Cache.<init>(Cache.java:208)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.paytm.network.FastDNS.getCache(FastDNS.java:84)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.paytm.network.FastDNS.init(FastDNS.java:64)
2019-08-06 14:03:52.381 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.paytm.network.FastDNS.lookup(FastDNS.java:37)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-06 14:03:52.382 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.paytm.network.OkHttpStack.executeRequest(OkHttpStack.java:136)
2019-08-06 14:03:52.383 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:131)
2019-08-06 14:03:52.384 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)
2019-08-06 14:03:52.384 4587-4620/network.paytm.com.networkmoduleapp W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
2019-08-06 14:03:52.384 4587-4620/network.paytm.com.networkmoduleapp D/ConnectionMatrices: Couldn't create file
**2019-08-06 14:03:52.389 4587-4620/network.paytm.com.networkmoduleapp E/libc: Access denied finding property "net.dns1"
2019-08-06 14:03:52.390 4587-4620/network.paytm.com.networkmoduleapp E/libc: Access denied finding property "net.dns2"
2019-08-06 14:03:52.390 4587-4620/network.paytm.com.networkmoduleapp E/libc: Access denied finding property "net.dns3"**

**Comment by ibauersachs** [comment]
You can load cache entries from a file as your example shows, but the file to load must exist. You must also write the file yourself (e.g. by calling toString() on the Cache object).
