### ISSUE TITLE
Resolver interface default method: setEDNS causes NPE

### ISSUE THREAD

**Issue by mwullink** [dnsjava/dnsjava#91]
Hi,

thx for the new 3.0 version, great work!
i encountered a small issue.

the setEDNS method in class Resolver has a param EDNSOption... options, looking in the code i thought i could just pass null value if i have no options.

But this will cause a NPE:
```
java.lang.NullPointerException: null
	at org.xbill.DNS.OPTRecord.rrToWire(OPTRecord.java:142) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.Record.toWire(Record.java:215) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.Record.toWire(Record.java:223) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.Message.toWire(Message.java:473) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.Message.toWire(Message.java:545) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.SimpleResolver.sendAsync(SimpleResolver.java:271) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.SimpleResolver.sendAsync(SimpleResolver.java:266) ~[dnsjava-3.0.0.jar:?]
	at org.xbill.DNS.Resolver.send(Resolver.java:145) ~[dnsjava-3.0.0.jar:?]
```
This because
calling the method like this: `myResolverObj.setEDNS(0, 4096, 0, (EDNSOption) null)`
will cause the options parameter to get the value of an array with a single null value:  options[null]

When writing the query to wireformat a NPE thrown.
```
  default void setEDNS(int version, int payloadSize, int flags, EDNSOption... options) {
    setEDNS(
        version,
        payloadSize,
        flags,
        options == null ? Collections.emptyList() : Arrays.asList(options));
  }
```

**Comment by ibauersachs** [comment]
Why are you calling setEDNS with an intentional null parameter and not simply `myResolverObj.setEDNS(0, 4096, 0)`?

**Comment by mwullink** [comment]
Ah yes, my bad!
of course you can just not use the optional last param.
please close this issue.
